# Generated by Django 3.2.8 on 2021-10-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromwellapp', '0002_rename_conf_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('cate_id', models.IntegerField(blank=True, null=True)),
                ('cate_name', models.CharField(blank=True, max_length=50, null=True)),
                ('proj_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
