# Generated by Django 3.2.8 on 2021-10-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cromwellapp', '0003_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configs',
            new_name='Config',
        ),
    ]
